name: Pack

on:
  push:
    branches: [main]

jobs:
  pack:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install .NET 5
        run: |
          sudo wget https://packages.microsoft.com/config/ubuntu/18.04/packages-microsoft-prod.deb -O packages-microsoft-prod.deb
          sudo dpkg -i packages-microsoft-prod.deb
            sudo apt-get install -y apt-transport-https && \
            sudo apt-get update && \
            sudo apt-get install -y dotnet-sdk-5.0
      - name: Install dependencies
        run: dotnet restore src/NScatterGather/NScatterGather.csproj
      - name: Build
        run: dotnet build src/NScatterGather/NScatterGather.csproj -c Release --no-restore
      - name: Install requirements
        run: |
          sudo apt-get install -y unzip
          sudo apt-get install -y xmlstarlet
          sudo apt-get install -y zip
      - name: Create package
        working-directory: ./pack
        run: sudo ./pack_nscattergather.sh
      - uses: actions/upload-artifact@v2
        with:
          name: nuget
          path: |
            pack/*.nupkg
            pack/*.snupkg
